spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    username: ${dataSource.user:sa}
    password: ${dataSource.password:123456}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      schema-locations: classpath:db/schema.sql
