spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    username: ${dataSource.user:sa}
    password: ${dataSource.password:123456}
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: create
